name: Download Articoli

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Esegui ogni giorno a mezzanotte

jobs:
  download-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download files (all except YouTube)
        run: |
          rm -rf articoli || true
          mkdir -p articoli
          cd articoli

          curl -s "https://www.regione.marche.it/jsons/rassegna_stampa_infrastrutture.csv?_=1744119555647" -o data.json

          sudo apt-get update && sudo apt-get install -y jq

          jq -r '.values[] | .[0]' data.json | while read -r url; do
            if [[ "$url" =~ [yY][oO][uU][tT][uU] ]]; then
              echo "⏭️ Skipping YouTube: $url"
              continue
            fi

            if [[ "$url" =~ ^/[pP][oO][rR][tT][aA][lL][sS] ]]; then
              url="https://www.regione.marche.it${url}"
            fi

            encoded_url=$(echo "$url" | sed -e 's/ /%20/g' -e 's/\[/%5B/g' -e 's/\]/%5D/g')
            filename=$(basename "$url" | sed -e 's/ /_/g' -e 's/[^a-zA-Z0-9._-]/_/g')

            echo "⬇️ Downloading: $encoded_url"
            
            curl -s -L -o "$filename" "$encoded_url" || echo "❌ Failed: $url"
          done

          rm data.json

      - name: Commit and push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add articoli/
          git diff --quiet && git diff --staged --quiet || git commit -m "🔄 Auto-update articoli $(date +'%d/%m/%Y')"
          git push