name: Unzip uploaded site files

on:
  push:
    paths:
      - 'downloads/site.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify ZIP exists
        run: |
          echo "Contenuto della cartella downloads/:"
          ls -la downloads/
          if [ -f "downloads/site.zip" ]; then
            echo "File ZIP trovato!"
          else
            echo "ERRORE: File ZIP non trovato"
            exit 1
          fi

      - name: Unzip files
        run: |
          rm -rf downloads/unzipped_site/* || true
          mkdir -p downloads/unzipped_site
          unzip -o downloads/site.zip -d downloads/unzipped_site/
          echo "File estratti:"
          ls -la downloads/unzipped_site/

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add downloads/unzipped_site/
          git commit -m "Extracted site files from ZIP [skip ci]" || echo "Nessun cambiamento da commitare"
          git push